# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoSyncApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoSyncApp
  pod 'Starscream', '~> 3.0.2'
  pod 'Alamofire', '~> 4.7'
  pod 'YouTubePlayer'
  pod 'Socket.IO-Client-Swift'
end
